version: "3"

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: fotolab
      MYSQL_USER: fotolab
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
    expose:
      - "3306"
  php:
    depends_on:
      - mysql
    container_name: fotolab-php
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    ports:
        - "9000:9000"
    volumes:
      - /d/projetos/pos-es-19-fotolab:/var/www
    networks:
      - laravel